### PR TITLE
Revert "Removing ties with Osclass Market."

### PR DESCRIPTION
**Pull request by navjottomer**
Reverts navjottomer/Osclass#22
There are functions which we may need and this brute-force deletion will increase the time and resource of further development. Make a new pull request with suggestions below.
Do not remove functions or class which are essentials for upgrading osclass, plugins and themes, Currently, they may call to official osclass market URLs but we can change them to use this repo or future repo for free plugins and themes. 
Make changes only which remove current build reliance on official osclass market.

### CODE REVIEW

**Comment by webmods-croatia** [comment]
Didn't see this earlier...

So I should
- disable (comment) cron update checking - it sents a request to Market.
- remove Market products from admin home
- remove Market page from admin?
- remove all links to Market (theme and plugin install)
- remove location selecting from installer
- anything else?

I would like to try to make a location selector on install that fetches location SQL from LoveOsclass repo. Maybe same with languages.

**Comment by navjottomer** [comment]
Exactly as you said in the above comment.
For location and languages, I have forked your GitHub repo and we can use this repo to install location and languages.

**Comment by dev-101** [comment]
Another possibility is self-containment. Only around +36.5 MB additional size.

**Comment by webmods-croatia** [comment]
> Another possibility is self-containment. Only around +36.5 MB additional size.

Interesting idea...

**Comment by webmods-croatia** [comment]
I don't have too much time to work on this, but I have done a few changes yesterday...
https://github.com/webmods-croatia/Osclass/tree/wm-patch2

**Pull request merged**
