### PR TITLE
Fix Market link

### PR DESCRIPTION
**Pull request by webmods-croatia**
@eurobank

### CODE REVIEW

**Comment by navjottomer** [comment]
A Suggestion for a future pull request, create a pull request from the correct branch.
It is hard to see from which branch you made this pull request.
It's better to have a same branch structure as the origin.

**Comment by webmods-croatia** [comment]
@navjottomer Can you explain better? I made a branch called wm-patch8 from release-3.9.0 branch.

**Comment by navjottomer** [comment]
You changed the target after making a pull request. I guessed you have made a pull request from develop branch. 
Anyway, it is merged.

**Comment by webmods-croatia** [comment]
Oh, I made from proper branch but selected wrong one when creating PR.

**Pull request merged**
