### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dev-101**

### CODE REVIEW

**Comment by webmods-croatia** [comment]
Installation guide/docs links can maybe be replaced with https://docs.osclasscommunity.com (will be improved), same with the forum (forums.osclasscommunity.com) if it's not a problem.

Note that Osclass Community is NOT a site that is made to earn money. There is no ads or anything, plugins on it's Market (market.osclasscommunity.com) are free as well.

**Comment by navjottomer** [comment]
> Installation guide/docs links can maybe be replaced with https://docs.osclasscommunity.com (will be improved), same with the forum (forums.osclasscommunity.com) if it's not a problem.
> 
> Note that Osclass Community is NOT a site that is made to earn money. There is no ads or anything, plugins on it's Market (market.osclasscommunity.com) are free as well.

Docs will be hosted on same repo or another osclass doc repo, so others can contribute to it. I am not interested in any market right now and for forums, I think we can safely provide a link directing to osclasscommunity.com.

**Comment by webmods-croatia** [comment]
Current docs are made with GitBook so others shouls be able to participate
easily. I need to check how to allow that or something.

čet, 26. ruj 2019. 19:14 Navjot Tomer <notifications@github.com> je napisao:

**Comment by webmods-croatia** [comment]
Or not. It's a paid feature on GitBook...

**Pull request merged**
