### PR TITLE
Params

### PR DESCRIPTION
**Pull request by web-media**
self::$_config gets created once 
This class needs a lot of work to be done  .

### CODE REVIEW

**Comment by web-media** [comment]
#140 related

**Comment by navjottomer** [comment]
I have made some changes to the Params class. This is not needed now.
Maybe you can help to create a new formatting class.
Will reopen it if existing changes do not cover the intent of this issue.

**Comment by web-media** [comment]
@navjottomer 
half of the issue  still here ,your code has multiple check if config is set  or not  on each Purify action beside if purifier is null  
it should check only if purifier is set 
```php
 if ($config_options !== null && is_array($config_options)) {
 elseif (!isset(self::$config)) {
```
and introduce another issues .
self::$purifier should be set to null each time you change the config 
double check 
```php
if (self::$purifier === null) 
```
 inside setHTMLPurifierInstance and each purify action
```php 
 public static function setHTMLPurifierInstance($config_options = null)
    {
        if ($config_options !== null && is_array($config_options)) {
            $config       = HTMLPurifier_Config::create($config_options);
            self::$config = $config;
        } elseif (!isset(self::$config)) {
            $config = HTMLPurifier_Config::createDefault();
            $config->set('HTML.Allowed', '');
            $config->set('Cache.SerializerPath', osc_uploads_path());
            self::$config = $config;
        }
        if (self::$purifier === null) {
            self::$purifier = new HTMLPurifier(self::$config);
        }
    }

    private static function purify($value, $xss_check)
    {
        if (!$xss_check) {
            return $value;
        }
        self::setHTMLPurifierInstance();
        if (!isset(self::$purifier)) {
            self::$purifier = new HTMLPurifier(self::$config);
        }
```

better aproach 
```php
 public static function init()
    {
        self::$_request = array_merge($_GET, $_POST);
        self::$_server  = $_SERVER;
        self::$_config = HTMLPurifier_Config::createDefault();
        self::$_config->autoFinalize = false;
        self::$_config->set('HTML.Allowed', '');
        self::$_config->set('Cache.SerializerPath', osc_uploads_path());
        self::$_purifier = new HTMLPurifier(self::$_config);
       
    }

    public function setConfig($key, $value) {
		
		self::$_purifier = null;
		self::$_config->set($key, $value); 
			
		} 
```

**Comment by web-media** [comment]
not a fan of singleton disguised into static class .i would leave responsibility of initialization to outside of the class and do avoid unnecessary calls to singleton instance .

**Comment by navjottomer** [comment]
Singleton and static methods are closer relatives, I don't mind if they mingle? ;-)
Right now I think than we should forget the HTMLPurifier extendability, it makes no sense in a static class. 
I think it would be better to leave purification to separated dedicated method only. 
I do not want to abuse init function to create HTMLPurifier config for minimal to no performance gain.
Better if we work on separate formatting class (You can create one and I'll merge it).

**Pull request closed without merging**
