### PR TITLE
Fix "Make primary image"

### PR DESCRIPTION
**Pull request by webmods-croatia**
Osclass actually haves "Make primary image" button when posting an item, but it's content is empty. There is no text.

https://github.com/navjottomer/Osclass/issues/35

### CODE REVIEW

**Comment by dev-101** [comment]
Hi, you are fixing/changing 3 different things with this PR. Don't do that. Instead, create separate PRs for each change. Also, why not using ITEM_LINK instead?

**Comment by webmods-croatia** [comment]
I noticed it minutes ago... I need a new branch for each fix, right?

**Comment by webmods-croatia** [comment]
ITEM_URL was used in most of the templates so I didn't change to ITEM_LINK.

**Comment by webmods-croatia** [comment]
Wrong branch... Sorry.

**Pull request closed without merging**
